# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# name: Build and deploy container app to Azure Web App - ShakescriptAI
#
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
#
# jobs:
#   build:
#     runs-on: 'ubuntu-latest'
#
#     steps:
#     - uses: actions/checkout@v2
#
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2
#
#     - name: Log in to registry
#       uses: docker/login-action@v2
#       with:
#         registry: https://index.docker.io/v1/
#         username: ${{ secrets.AzureAppService_ContainerUsername_2819fddc25c8481ba3f10d887d08ec9d }}
#         password: ${{ secrets.AzureAppService_ContainerPassword_ab5401f8d1484e8b9d31af65f04c79b3 }}
#
#     - name: Build and push container image to registry
#       uses: docker/build-push-action@v3
#       with:
#         push: true
#         tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2819fddc25c8481ba3f10d887d08ec9d }}/shakescript-backend:${{ github.sha }}
#         file: ./dockerfile
#
#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#     steps:
#     - name: Deploy to Azure Web App
#       id: deploy-to-webapp
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'ShakescriptAI'
#         slot-name: 'production'
#         publish-profile: ${{ secrets.AzureAppService_PublishProfile_ef8dd818767f4980ad51c7332f9054d1 }}
#         images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2819fddc25c8481ba3f10d887d08ec9d }}/shakescript-backend:${{ github.sha }}'
